name: Build

on:
  push:
    branches:
      - "main"
    paths:
      - "Source/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "Source/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.102"

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release
